[package]
name = "Meson-Contracts-Move"
version = "0.1.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "main" }

[addresses]
std = "0x1"
aptos_token = "0x3"
Meson = "0x0b12937a1a7a6d86e22cd372332839dda585f36dace804c5e516b81eba91663e"
